package com.neuedu.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class ItemOrderBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemorder.iid
     *
     * @mbg.generated
     */
    private Integer iid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemorder.ocode
     *
     * @mbg.generated
     */
    private Long ocode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemorder.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemorder.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemorder.pname
     *
     * @mbg.generated
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemorder.mainImage
     *
     * @mbg.generated
     */
    private String mainimage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemorder.finalprice
     *
     * @mbg.generated
     */
    private BigDecimal finalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemorder.camount
     *
     * @mbg.generated
     */
    private Integer camount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemorder.totalprice
     *
     * @mbg.generated
     */
    private BigDecimal totalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemorder.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itemorder.updateTime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemorder.iid
     *
     * @return the value of itemorder.iid
     *
     * @mbg.generated
     */
    public Integer getIid() {
        return iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemorder.iid
     *
     * @param iid the value for itemorder.iid
     *
     * @mbg.generated
     */
    public void setIid(Integer iid) {
        this.iid = iid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemorder.ocode
     *
     * @return the value of itemorder.ocode
     *
     * @mbg.generated
     */
    public Long getOcode() {
        return ocode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemorder.ocode
     *
     * @param ocode the value for itemorder.ocode
     *
     * @mbg.generated
     */
    public void setOcode(Long ocode) {
        this.ocode = ocode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemorder.uid
     *
     * @return the value of itemorder.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemorder.uid
     *
     * @param uid the value for itemorder.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemorder.pid
     *
     * @return the value of itemorder.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemorder.pid
     *
     * @param pid the value for itemorder.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemorder.pname
     *
     * @return the value of itemorder.pname
     *
     * @mbg.generated
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemorder.pname
     *
     * @param pname the value for itemorder.pname
     *
     * @mbg.generated
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemorder.mainImage
     *
     * @return the value of itemorder.mainImage
     *
     * @mbg.generated
     */
    public String getMainimage() {
        return mainimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemorder.mainImage
     *
     * @param mainimage the value for itemorder.mainImage
     *
     * @mbg.generated
     */
    public void setMainimage(String mainimage) {
        this.mainimage = mainimage == null ? null : mainimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemorder.finalprice
     *
     * @return the value of itemorder.finalprice
     *
     * @mbg.generated
     */
    public BigDecimal getFinalprice() {
        return finalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemorder.finalprice
     *
     * @param finalprice the value for itemorder.finalprice
     *
     * @mbg.generated
     */
    public void setFinalprice(BigDecimal finalprice) {
        this.finalprice = finalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemorder.camount
     *
     * @return the value of itemorder.camount
     *
     * @mbg.generated
     */
    public Integer getCamount() {
        return camount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemorder.camount
     *
     * @param camount the value for itemorder.camount
     *
     * @mbg.generated
     */
    public void setCamount(Integer camount) {
        this.camount = camount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemorder.totalprice
     *
     * @return the value of itemorder.totalprice
     *
     * @mbg.generated
     */
    public BigDecimal getTotalprice() {
        return totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemorder.totalprice
     *
     * @param totalprice the value for itemorder.totalprice
     *
     * @mbg.generated
     */
    public void setTotalprice(BigDecimal totalprice) {
        this.totalprice = totalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemorder.createTime
     *
     * @return the value of itemorder.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemorder.createTime
     *
     * @param createtime the value for itemorder.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itemorder.updateTime
     *
     * @return the value of itemorder.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itemorder.updateTime
     *
     * @param updatetime the value for itemorder.updateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}