package com.neuedu.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class OrdersBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.oid
     *
     * @mbg.generated
     */
    private Integer oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ocode
     *
     * @mbg.generated
     */
    private Integer ocode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.ostatus
     *
     * @mbg.generated
     */
    private Integer ostatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.opayment
     *
     * @mbg.generated
     */
    private BigDecimal opayment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.opaymentType
     *
     * @mbg.generated
     */
    private Integer opaymenttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.sid
     *
     * @mbg.generated
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.opostage
     *
     * @mbg.generated
     */
    private BigDecimal opostage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.opaymentTime
     *
     * @mbg.generated
     */
    private Date opaymenttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.sendTime
     *
     * @mbg.generated
     */
    private Date sendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.closeTime
     *
     * @mbg.generated
     */
    private Date closetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.endTime
     *
     * @mbg.generated
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.updateTime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.oid
     *
     * @return the value of orders.oid
     *
     * @mbg.generated
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.oid
     *
     * @param oid the value for orders.oid
     *
     * @mbg.generated
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ocode
     *
     * @return the value of orders.ocode
     *
     * @mbg.generated
     */
    public Integer getOcode() {
        return ocode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ocode
     *
     * @param ocode the value for orders.ocode
     *
     * @mbg.generated
     */
    public void setOcode(Integer ocode) {
        this.ocode = ocode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.ostatus
     *
     * @return the value of orders.ostatus
     *
     * @mbg.generated
     */
    public Integer getOstatus() {
        return ostatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.ostatus
     *
     * @param ostatus the value for orders.ostatus
     *
     * @mbg.generated
     */
    public void setOstatus(Integer ostatus) {
        this.ostatus = ostatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.uid
     *
     * @return the value of orders.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.uid
     *
     * @param uid the value for orders.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.opayment
     *
     * @return the value of orders.opayment
     *
     * @mbg.generated
     */
    public BigDecimal getOpayment() {
        return opayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.opayment
     *
     * @param opayment the value for orders.opayment
     *
     * @mbg.generated
     */
    public void setOpayment(BigDecimal opayment) {
        this.opayment = opayment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.opaymentType
     *
     * @return the value of orders.opaymentType
     *
     * @mbg.generated
     */
    public Integer getOpaymenttype() {
        return opaymenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.opaymentType
     *
     * @param opaymenttype the value for orders.opaymentType
     *
     * @mbg.generated
     */
    public void setOpaymenttype(Integer opaymenttype) {
        this.opaymenttype = opaymenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.sid
     *
     * @return the value of orders.sid
     *
     * @mbg.generated
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.sid
     *
     * @param sid the value for orders.sid
     *
     * @mbg.generated
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.opostage
     *
     * @return the value of orders.opostage
     *
     * @mbg.generated
     */
    public BigDecimal getOpostage() {
        return opostage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.opostage
     *
     * @param opostage the value for orders.opostage
     *
     * @mbg.generated
     */
    public void setOpostage(BigDecimal opostage) {
        this.opostage = opostage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.opaymentTime
     *
     * @return the value of orders.opaymentTime
     *
     * @mbg.generated
     */
    public Date getOpaymenttime() {
        return opaymenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.opaymentTime
     *
     * @param opaymenttime the value for orders.opaymentTime
     *
     * @mbg.generated
     */
    public void setOpaymenttime(Date opaymenttime) {
        this.opaymenttime = opaymenttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.sendTime
     *
     * @return the value of orders.sendTime
     *
     * @mbg.generated
     */
    public Date getSendtime() {
        return sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.sendTime
     *
     * @param sendtime the value for orders.sendTime
     *
     * @mbg.generated
     */
    public void setSendtime(Date sendtime) {
        this.sendtime = sendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.closeTime
     *
     * @return the value of orders.closeTime
     *
     * @mbg.generated
     */
    public Date getClosetime() {
        return closetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.closeTime
     *
     * @param closetime the value for orders.closeTime
     *
     * @mbg.generated
     */
    public void setClosetime(Date closetime) {
        this.closetime = closetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.endTime
     *
     * @return the value of orders.endTime
     *
     * @mbg.generated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.endTime
     *
     * @param endtime the value for orders.endTime
     *
     * @mbg.generated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.createTime
     *
     * @return the value of orders.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.createTime
     *
     * @param createtime the value for orders.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.updateTime
     *
     * @return the value of orders.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.updateTime
     *
     * @param updatetime the value for orders.updateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}