package com.neuedu.pojo;

import java.util.Date;

public class PayInfoBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payinfo.payinfoid
     *
     * @mbg.generated
     */
    private Integer payinfoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payinfo.ocode
     *
     * @mbg.generated
     */
    private Long ocode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payinfo.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payinfo.paymentType
     *
     * @mbg.generated
     */
    private Integer paymenttype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payinfo.paystatus
     *
     * @mbg.generated
     */
    private String paystatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payinfo.paynumber
     *
     * @mbg.generated
     */
    private String paynumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payinfo.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payinfo.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payinfo.payinfoid
     *
     * @return the value of payinfo.payinfoid
     *
     * @mbg.generated
     */
    public Integer getPayinfoid() {
        return payinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payinfo.payinfoid
     *
     * @param payinfoid the value for payinfo.payinfoid
     *
     * @mbg.generated
     */
    public void setPayinfoid(Integer payinfoid) {
        this.payinfoid = payinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payinfo.ocode
     *
     * @return the value of payinfo.ocode
     *
     * @mbg.generated
     */
    public Long getOcode() {
        return ocode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payinfo.ocode
     *
     * @param ocode the value for payinfo.ocode
     *
     * @mbg.generated
     */
    public void setOcode(Long ocode) {
        this.ocode = ocode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payinfo.uid
     *
     * @return the value of payinfo.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payinfo.uid
     *
     * @param uid the value for payinfo.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payinfo.paymentType
     *
     * @return the value of payinfo.paymentType
     *
     * @mbg.generated
     */
    public Integer getPaymenttype() {
        return paymenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payinfo.paymentType
     *
     * @param paymenttype the value for payinfo.paymentType
     *
     * @mbg.generated
     */
    public void setPaymenttype(Integer paymenttype) {
        this.paymenttype = paymenttype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payinfo.paystatus
     *
     * @return the value of payinfo.paystatus
     *
     * @mbg.generated
     */
    public String getPaystatus() {
        return paystatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payinfo.paystatus
     *
     * @param paystatus the value for payinfo.paystatus
     *
     * @mbg.generated
     */
    public void setPaystatus(String paystatus) {
        this.paystatus = paystatus == null ? null : paystatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payinfo.paynumber
     *
     * @return the value of payinfo.paynumber
     *
     * @mbg.generated
     */
    public String getPaynumber() {
        return paynumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payinfo.paynumber
     *
     * @param paynumber the value for payinfo.paynumber
     *
     * @mbg.generated
     */
    public void setPaynumber(String paynumber) {
        this.paynumber = paynumber == null ? null : paynumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payinfo.create_time
     *
     * @return the value of payinfo.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payinfo.create_time
     *
     * @param createTime the value for payinfo.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payinfo.update_time
     *
     * @return the value of payinfo.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payinfo.update_time
     *
     * @param updateTime the value for payinfo.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}