package com.neuedu.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class ProductBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pname
     *
     * @mbg.generated
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.tid
     *
     * @mbg.generated
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.ptitle
     *
     * @mbg.generated
     */
    private String ptitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.mainImage
     *
     * @mbg.generated
     */
    private String mainimage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.subImage
     *
     * @mbg.generated
     */
    private String subimage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pstock
     *
     * @mbg.generated
     */
    private Integer pstock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pstatus
     *
     * @mbg.generated
     */
    private Integer pstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.updateTime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pdetail
     *
     * @mbg.generated
     */
    private String pdetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pid
     *
     * @return the value of product.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pid
     *
     * @param pid the value for product.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pname
     *
     * @return the value of product.pname
     *
     * @mbg.generated
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pname
     *
     * @param pname the value for product.pname
     *
     * @mbg.generated
     */
    public void setPname(String pname) {
        this.pname = pname == null ? null : pname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.tid
     *
     * @return the value of product.tid
     *
     * @mbg.generated
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.tid
     *
     * @param tid the value for product.tid
     *
     * @mbg.generated
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.ptitle
     *
     * @return the value of product.ptitle
     *
     * @mbg.generated
     */
    public String getPtitle() {
        return ptitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.ptitle
     *
     * @param ptitle the value for product.ptitle
     *
     * @mbg.generated
     */
    public void setPtitle(String ptitle) {
        this.ptitle = ptitle == null ? null : ptitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.mainImage
     *
     * @return the value of product.mainImage
     *
     * @mbg.generated
     */
    public String getMainimage() {
        return mainimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.mainImage
     *
     * @param mainimage the value for product.mainImage
     *
     * @mbg.generated
     */
    public void setMainimage(String mainimage) {
        this.mainimage = mainimage == null ? null : mainimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.subImage
     *
     * @return the value of product.subImage
     *
     * @mbg.generated
     */
    public String getSubimage() {
        return subimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.subImage
     *
     * @param subimage the value for product.subImage
     *
     * @mbg.generated
     */
    public void setSubimage(String subimage) {
        this.subimage = subimage == null ? null : subimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pstock
     *
     * @return the value of product.pstock
     *
     * @mbg.generated
     */
    public Integer getPstock() {
        return pstock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pstock
     *
     * @param pstock the value for product.pstock
     *
     * @mbg.generated
     */
    public void setPstock(Integer pstock) {
        this.pstock = pstock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pstatus
     *
     * @return the value of product.pstatus
     *
     * @mbg.generated
     */
    public Integer getPstatus() {
        return pstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pstatus
     *
     * @param pstatus the value for product.pstatus
     *
     * @mbg.generated
     */
    public void setPstatus(Integer pstatus) {
        this.pstatus = pstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.createTime
     *
     * @return the value of product.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.createTime
     *
     * @param createtime the value for product.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.updateTime
     *
     * @return the value of product.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.updateTime
     *
     * @param updatetime the value for product.updateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pdetail
     *
     * @return the value of product.pdetail
     *
     * @mbg.generated
     */
    public String getPdetail() {
        return pdetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pdetail
     *
     * @param pdetail the value for product.pdetail
     *
     * @mbg.generated
     */
    public void setPdetail(String pdetail) {
        this.pdetail = pdetail == null ? null : pdetail.trim();
    }
}