package com.neuedu.pojo;

import java.util.Date;

public class TypeBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.tid
     *
     * @mbg.generated
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.tname
     *
     * @mbg.generated
     */
    private String tname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.tparentId
     *
     * @mbg.generated
     */
    private Integer tparentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.tstatus
     *
     * @mbg.generated
     */
    private Integer tstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.updateTime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.tid
     *
     * @return the value of type.tid
     *
     * @mbg.generated
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.tid
     *
     * @param tid the value for type.tid
     *
     * @mbg.generated
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.tname
     *
     * @return the value of type.tname
     *
     * @mbg.generated
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.tname
     *
     * @param tname the value for type.tname
     *
     * @mbg.generated
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.tparentId
     *
     * @return the value of type.tparentId
     *
     * @mbg.generated
     */
    public Integer getTparentid() {
        return tparentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.tparentId
     *
     * @param tparentid the value for type.tparentId
     *
     * @mbg.generated
     */
    public void setTparentid(Integer tparentid) {
        this.tparentid = tparentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.tstatus
     *
     * @return the value of type.tstatus
     *
     * @mbg.generated
     */
    public Integer getTstatus() {
        return tstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.tstatus
     *
     * @param tstatus the value for type.tstatus
     *
     * @mbg.generated
     */
    public void setTstatus(Integer tstatus) {
        this.tstatus = tstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.createTime
     *
     * @return the value of type.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.createTime
     *
     * @param createtime the value for type.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.updateTime
     *
     * @return the value of type.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.updateTime
     *
     * @param updatetime the value for type.updateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}