package com.neuedu.pojo;

import java.util.Date;

public class UserBean {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uname
     *
     * @mbg.generated
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.upwd
     *
     * @mbg.generated
     */
    private String upwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.umonicker
     *
     * @mbg.generated
     */
    private String umonicker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uemail
     *
     * @mbg.generated
     */
    private String uemail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uphone
     *
     * @mbg.generated
     */
    private String uphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uquestion
     *
     * @mbg.generated
     */
    private String uquestion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.uanswer
     *
     * @mbg.generated
     */
    private String uanswer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.urole
     *
     * @mbg.generated
     */
    private Integer urole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.updateTime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uid
     *
     * @return the value of user.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uid
     *
     * @param uid the value for user.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uname
     *
     * @return the value of user.uname
     *
     * @mbg.generated
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uname
     *
     * @param uname the value for user.uname
     *
     * @mbg.generated
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.upwd
     *
     * @return the value of user.upwd
     *
     * @mbg.generated
     */
    public String getUpwd() {
        return upwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.upwd
     *
     * @param upwd the value for user.upwd
     *
     * @mbg.generated
     */
    public void setUpwd(String upwd) {
        this.upwd = upwd == null ? null : upwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.umonicker
     *
     * @return the value of user.umonicker
     *
     * @mbg.generated
     */
    public String getUmonicker() {
        return umonicker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.umonicker
     *
     * @param umonicker the value for user.umonicker
     *
     * @mbg.generated
     */
    public void setUmonicker(String umonicker) {
        this.umonicker = umonicker == null ? null : umonicker.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uemail
     *
     * @return the value of user.uemail
     *
     * @mbg.generated
     */
    public String getUemail() {
        return uemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uemail
     *
     * @param uemail the value for user.uemail
     *
     * @mbg.generated
     */
    public void setUemail(String uemail) {
        this.uemail = uemail == null ? null : uemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uphone
     *
     * @return the value of user.uphone
     *
     * @mbg.generated
     */
    public String getUphone() {
        return uphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uphone
     *
     * @param uphone the value for user.uphone
     *
     * @mbg.generated
     */
    public void setUphone(String uphone) {
        this.uphone = uphone == null ? null : uphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uquestion
     *
     * @return the value of user.uquestion
     *
     * @mbg.generated
     */
    public String getUquestion() {
        return uquestion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uquestion
     *
     * @param uquestion the value for user.uquestion
     *
     * @mbg.generated
     */
    public void setUquestion(String uquestion) {
        this.uquestion = uquestion == null ? null : uquestion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.uanswer
     *
     * @return the value of user.uanswer
     *
     * @mbg.generated
     */
    public String getUanswer() {
        return uanswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.uanswer
     *
     * @param uanswer the value for user.uanswer
     *
     * @mbg.generated
     */
    public void setUanswer(String uanswer) {
        this.uanswer = uanswer == null ? null : uanswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.urole
     *
     * @return the value of user.urole
     *
     * @mbg.generated
     */
    public Integer getUrole() {
        return urole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.urole
     *
     * @param urole the value for user.urole
     *
     * @mbg.generated
     */
    public void setUrole(Integer urole) {
        this.urole = urole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.createTime
     *
     * @return the value of user.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.createTime
     *
     * @param createtime the value for user.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.updateTime
     *
     * @return the value of user.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.updateTime
     *
     * @param updatetime the value for user.updateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}