package com.neuedu.dao;

import com.neuedu.pojo.ItemOrderBean;
import java.util.List;

public interface ItemOrderBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemorder
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer iid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemorder
     *
     * @mbg.generated
     */
    int insert(ItemOrderBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemorder
     *
     * @mbg.generated
     */
    ItemOrderBean selectByPrimaryKey(Integer iid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemorder
     *
     * @mbg.generated
     */
    List<ItemOrderBean> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itemorder
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ItemOrderBean record);
}