package com.neuedu.dao;

import com.neuedu.pojo.PayInfoBean;
import java.util.List;

public interface PayInfoBeanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payinfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer payinfoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payinfo
     *
     * @mbg.generated
     */
    int insert(PayInfoBean record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payinfo
     *
     * @mbg.generated
     */
    PayInfoBean selectByPrimaryKey(Integer payinfoid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payinfo
     *
     * @mbg.generated
     */
    List<PayInfoBean> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payinfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PayInfoBean record);
}